database:
  host: localhost
  database: Skyblock
  username: username
  password: password
  port: 3306

redis:
  enable: false # Set to true if using multiple proxies

  host: localhost
  port: 0 # Set to 0 or remove this line for default port
  password: "" # Set empty or remove this line for no password