database:
  # Available types: SQLite, MySQL, MONGODB
  type: SQLite

  # Specific to MySQL, leave blank with SQLite
  host: localhost
  database: Skyblock
  username: username  # Leave blank for MongoDB
  password: password  # Leave blank for MongoDB
  port: 3306